[package]
name = "pbps-load"
description = "PongBiphang Schema - YAML loading, diagnostics and canonical rendering"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
pbps-model.workspace = true
indexmap.workspace = true
serde.workspace = true
schemars.workspace = true
serde_json.workspace = true
serde-saphyr.workspace = true
miette.workspace = true
thiserror.workspace = true

[lints]
workspace = true

[dev-dependencies]
miette = { workspace = true, features = ["fancy"] }
