[package]
name = "pbps-docs"
description = "PongBiphang Schema - documentation and ERD rendering"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
pbps-model.workspace = true

[lints]
workspace = true
