//! Complete, source-independent runtime inputs; read-only is not private.

use super::{ProcessLease, UnqualifiedProcess, open_within, read_bounded_from};
use rustix::fs::{OFlags, StatVfsMountFlags, fstatvfs};

pub(crate) const HOSTNAME: &str = "pbps-resolver";

// These are the complete measured Docker files for network=none with every
// DNS field overridden. Comments are data too: parsing only resolver options
// would silently admit host search domains or addresses in ignored lines.
const FILES: [(&str, &str); 3] = [
    ("etc/hostname", "pbps-resolver\n"),
    (
        "etc/hosts",
        concat!(
            "127.0.0.1\tlocalhost\n",
            "::1\tlocalhost ip6-localhost ip6-loopback\n",
            "fe00::\tip6-localnet\n",
            "ff00::\tip6-mcastprefix\n",
            "ff02::1\tip6-allnodes\n",
            "ff02::2\tip6-allrouters\n",
        ),
    ),
    (
        "etc/resolv.conf",
        concat!(
            "# Generated by Docker Engine.\n",
            "# This file can be edited; Docker Engine will not make further changes once it\n",
            "# has been modified.\n\n",
            "nameserver 127.0.0.1\n",
            "options ndots:0\n\n",
            "# Based on host file: '/etc/resolv.conf' (legacy)\n",
            "# Overrides: [nameservers search options]\n",
            "# Option ndots from: override\n",
        ),
    ),
];

pub(crate) fn check(process: &ProcessLease) -> Result<(), UnqualifiedProcess> {
    process.check()?;
    let root = process.root()?;
    for (path, expected) in FILES {
        // NONBLOCK lets us reject a substituted FIFO without waiting for a
        // writer. Resolve beneath the held process root, never the host root.
        let file = open_within(&root, path, OFlags::NOFOLLOW | OFlags::NONBLOCK)
            .map_err(|_| UnqualifiedProcess)?;
        if !file.metadata().map_err(|_| UnqualifiedProcess)?.is_file()
            || !fstatvfs(&file)
                .map_err(|_| UnqualifiedProcess)?
                .f_flag
                .contains(StatVfsMountFlags::RDONLY)
        {
            return Err(UnqualifiedProcess);
        }
        let actual = read_bounded_from(file, expected.len())?;
        // NetworkDisabled=true on the measured Docker API leaves these files
        // empty; network=none alone generates the fixed layout above. Empty
        // is safe only after opening and qualifying the actual regular file.
        if !actual.is_empty() && actual != expected {
            return Err(UnqualifiedProcess);
        }
    }
    process.check()
}
