[package]
name = "pbps-db"
description = "PongBiphang Schema - database connections"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
thiserror.workspace = true
tiberius.workspace = true
tokio.workspace = true
tokio-util.workspace = true

[lints]
workspace = true
