//! Reading a live PostgreSQL back into the model: the pure half.
//!
//! The split is [`crate::catalog`]'s doc comment's, and it is the one the SQL
//! Server crate uses for the same reason: **only the query file talks to a
//! server**. It turns `pg_catalog` rows into the plain `Raw*` structs below and
//! hands them to [`assemble`], which is a function of its input and testable
//! with no server at all. Every rule about what the model can and cannot hold
//! lives here, where a test can reach it.
//!
//! # What this half must never do
//!
//! **Absent, empty and unreadable are three different things** (CLAUDE.md), and
//! introspection is where that rule earns its keep. A catalog row this code
//! cannot express does not vanish and does not become a plausible guess: it
//! becomes a [`Limitation`], carried out beside the schema so the caller can
//! show it. Drift that pbps cannot see is worse than drift it reports and
//! cannot fix, because only the second kind is visible to the operator.
//!
//! # Two ways of not being able to hold something
//!
//! A fact this model cannot carry is always named. What differs is whether the
//! object it belongs to is carried anyway, and the line is what the difference
//! is *about*:
//!
//! - **A property of the object itself** — `RESTRICT`, `DEFERRABLE`, a `gin`
//!   index, an expression index — means the object is **left out**. Carried, it
//!   would compare equal to one that behaves differently, and a plan would
//!   report no change while the behaviour stayed wrong. Left out, the plan is
//!   wrong in the direction that fails loudly on apply, and the warning says
//!   why.
//! - **A fact about the rows already there** — `NOT VALID` — means the object
//!   is **carried**, because the object itself is exactly what the model says.
//!   What recreating it would change is which rows get checked, and that is a
//!   plan that fails on apply rather than one that lies.
//!
//! **It must not un-respell anything** (ADR-0009 §2). PostgreSQL rewrites what
//! it was given — `'x'` becomes `'x'::character varying`, `CHECK (amount >= 0)`
//! becomes `CHECK ((amount >= (0)::numeric))` — and the state's `declared`
//! record (DECISIONS 207-209) is what makes the comparison honest. A normalizer
//! here would hide exactly the difference the record exists to make visible, so
//! the three verbatim expressions — a column's default, a check's expression
//! and an index's filter — are carried through untouched.

use std::collections::{BTreeMap, BTreeSet, HashMap};

use pbps_model::{
    CheckConstraint, Column, ColumnType, ForeignKey, Identity, Index, IndexColumn, PrimaryKey,
    ReferentialAction, Schema, Table, TableName, UniqueConstraint,
};

use crate::types;

/// One ordinary table, as `pg_class` has it.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct RawTable {
    pub oid: i64,
    pub schema: String,
    pub name: String,
}

/// One live column of one table.
///
/// A dropped column never reaches here: the catalog keeps its slot with a
/// placeholder name and no readable type (ADR-0012 §6), and the query filters
/// `attisdropped`. `attnum` is kept all the same, because it is what
/// `pg_constraint.conkey` and `pg_index.indkey` refer to — and because the
/// dropped slot leaves a **hole** in it, so it is an identifier and never a
/// position.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct RawColumn {
    pub table_oid: i64,
    pub attnum: i32,
    pub name: String,
    /// `format_type(atttypid, atttypmod)`: the engine's own spelling.
    pub ty: String,
    pub nullable: bool,
    /// `pg_get_expr(adbin, adrelid)`, verbatim, cast and all.
    pub default: Option<String>,
    /// `attidentity`: `a` for ALWAYS, `d` for BY DEFAULT, empty for neither.
    pub identity: Option<RawIdentity>,
    /// `attgenerated`: `s` for a stored generated column, empty for neither.
    pub generated: bool,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct RawIdentity {
    /// `true` for `GENERATED ALWAYS`, `false` for `GENERATED BY DEFAULT`.
    pub always: bool,
    pub seed: i64,
    pub increment: i64,
}

/// One row of `pg_constraint`, whatever its kind.
///
/// The kind is kept as the engine's own character rather than parsed into an
/// enum here, because the set is open at the engine's end: PostgreSQL 18 added
/// `n` for a catalogued NOT NULL, and a reader that had folded the characters
/// it knew into an enum and everything else into "a check" would have started
/// reporting one phantom check per NOT NULL column on an engine upgrade.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct RawConstraint {
    pub table_oid: i64,
    pub name: String,
    /// `contype`: `p` primary key, `u` unique, `f` foreign key, `c` check,
    /// `n` not null (PostgreSQL 18+), `x` exclusion, `t` constraint trigger.
    pub kind: char,
    /// `conkey`, the constrained columns as **attnums**.
    pub columns: Vec<i32>,
    /// `confkey`, the referenced columns as attnums, for a foreign key.
    pub ref_columns: Vec<i32>,
    /// `confrelid`, the referenced table.
    pub ref_table: Option<i64>,
    /// `confdeltype` and `confupdtype`: `a` NO ACTION, `r` RESTRICT,
    /// `c` CASCADE, `n` SET NULL, `d` SET DEFAULT.
    pub on_delete: char,
    pub on_update: char,
    /// `convalidated`. A constraint declared `NOT VALID` has never been checked
    /// against the rows already there.
    pub validated: bool,
    /// `condeferrable` and `condeferred`. A key whose check can be put off to
    /// the end of the transaction is a different key: rows that violate it may
    /// legally exist in the middle of one.
    pub deferrable: bool,
    pub deferred: bool,
    /// `pg_get_constraintdef`, verbatim.
    pub definition: String,
    /// `conindid`: the index this constraint is enforced by, if any. It is how
    /// a unique index that *is* a constraint is told from one that is not.
    pub index_oid: Option<i64>,
}

/// One row of `pg_index`, joined to what it needs from `pg_class` and `pg_am`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct RawIndex {
    pub oid: i64,
    pub table_oid: i64,
    pub name: String,
    pub unique: bool,
    pub primary: bool,
    pub exclusion: bool,
    /// `indnkeyatts`: how many of `columns` are key columns. The rest are the
    /// `INCLUDE` payload.
    pub key_count: usize,
    /// `indkey`, as attnums. A `0` is an expression rather than a column.
    pub columns: Vec<i32>,
    /// `indoption` per column; bit 0 is DESC, bit 1 is NULLS FIRST.
    pub options: Vec<i32>,
    /// `pg_get_expr(indpred, indrelid)`, verbatim.
    pub filter: Option<String>,
    /// Whether `indexprs` is set: the index is over an expression.
    pub has_expressions: bool,
    /// `amname`: `btree`, `hash`, `gin`, …
    pub method: String,
}

/// Everything one pull read, before any of it is interpreted.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct RawCatalog {
    pub tables: Vec<RawTable>,
    pub columns: Vec<RawColumn>,
    pub constraints: Vec<RawConstraint>,
    pub indexes: Vec<RawIndex>,
}

/// One fact about the database that the model cannot hold.
///
/// It carries the table it belongs to so that a caller can tell a limitation
/// inside the managed set — which is drift it must not call clean — from one on
/// a table this project does not declare.
#[derive(Debug, Clone, PartialEq, Eq, PartialOrd, Ord)]
pub struct Limitation {
    pub table: TableName,
    pub detail: String,
}

/// The result of a pull: the schema, and everything that could not be said.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct Pulled {
    pub schema: Schema,
    /// Every limitation, rendered, in the order a reader should see them.
    /// Never empty silence — see this module's own documentation.
    pub warnings: Vec<String>,
    pub limitations: Vec<Limitation>,
}

/// The engine's referential action characters.
///
/// `RESTRICT` has no [`ReferentialAction`] to map onto, and the difference is
/// not cosmetic: `NO ACTION` is deferrable and checked at the end of the
/// statement, `RESTRICT` is not. Folding one into the other would let a plan
/// silently replace a foreign key's behaviour, so it is refused and reported.
fn referential_action(c: char) -> Option<ReferentialAction> {
    match c {
        'a' => Some(ReferentialAction::NoAction),
        'c' => Some(ReferentialAction::Cascade),
        'n' => Some(ReferentialAction::SetNull),
        'd' => Some(ReferentialAction::SetDefault),
        _ => None,
    }
}

fn action_name(c: char) -> &'static str {
    match c {
        'a' => "NO ACTION",
        'r' => "RESTRICT",
        'c' => "CASCADE",
        'n' => "SET NULL",
        'd' => "SET DEFAULT",
        _ => "an action this engine spells with a character pbps does not know",
    }
}

/// Everything a table's own assembly needs, gathered once.
struct Parts<'a> {
    name: TableName,
    /// attnum to column name. Built from the live columns, so a dropped slot
    /// is simply not in it — which is what makes an unresolvable attnum a
    /// reportable fact rather than an off-by-one.
    by_attnum: HashMap<i32, &'a str>,
}

impl Parts<'_> {
    /// The names behind a list of attnums, or the first attnum that has none.
    fn names(&self, attnums: &[i32]) -> Result<Vec<String>, i32> {
        attnums
            .iter()
            .map(|n| self.by_attnum.get(n).map(|s| (*s).to_owned()).ok_or(*n))
            .collect()
    }
}

/// Turns one pull's rows into a [`Schema`] and the list of what it could not
/// hold.
///
/// Pure: every decision here is a function of `raw`, and every one of them is
/// reachable from a unit test.
pub fn assemble(raw: &RawCatalog) -> Pulled {
    let mut pulled = Pulled::default();

    let columns_by_table = group(&raw.columns, |c| c.table_oid);
    let constraints_by_table = group(&raw.constraints, |c| c.table_oid);
    let indexes_by_table = group(&raw.indexes, |i| i.table_oid);
    let table_names: HashMap<i64, TableName> = raw
        .tables
        .iter()
        .map(|t| (t.oid, TableName::new(&t.schema, &t.name)))
        .collect();

    // An index that enforces a constraint is that constraint, and reporting it
    // again under `indexes:` would make every primary key look like a primary
    // key plus a unique index — a difference the differ would then try to
    // remove, by dropping an index the engine will not let go of.
    let constraint_indexes: BTreeSet<i64> =
        raw.constraints.iter().filter_map(|c| c.index_oid).collect();

    for raw_table in &raw.tables {
        let name = TableName::new(&raw_table.schema, &raw_table.name);
        let raw_columns = columns_by_table
            .get(&raw_table.oid)
            .map_or(&[][..], Vec::as_slice);
        let parts = Parts {
            name: name.clone(),
            by_attnum: raw_columns
                .iter()
                .map(|c| (c.attnum, c.name.as_str()))
                .collect(),
        };

        let mut table = Table {
            columns: raw_columns
                .iter()
                .map(|c| (c.name.clone(), column(c, &parts, &mut pulled)))
                .collect(),
            ..Table::default()
        };

        for constraint in constraints_by_table
            .get(&raw_table.oid)
            .map_or(&[][..], Vec::as_slice)
        {
            add_constraint(constraint, &parts, &table_names, &mut table, &mut pulled);
        }
        for index in indexes_by_table
            .get(&raw_table.oid)
            .map_or(&[][..], Vec::as_slice)
        {
            if constraint_indexes.contains(&index.oid) {
                continue;
            }
            add_index(index, &parts, &mut table, &mut pulled);
        }

        pulled.schema.tables.insert(name, table);
    }

    pulled
}

fn group<T, K: Ord + Copy>(items: &[T], key: impl Fn(&T) -> K) -> BTreeMap<K, Vec<&T>> {
    let mut out: BTreeMap<K, Vec<&T>> = BTreeMap::new();
    for item in items {
        out.entry(key(item)).or_default().push(item);
    }
    out
}

fn note(pulled: &mut Pulled, table: &TableName, detail: String) {
    pulled.warnings.push(detail.clone());
    pulled.limitations.push(Limitation {
        table: table.clone(),
        detail,
    });
}

/// One column, and everything about it the model has nowhere to put.
fn column(raw: &RawColumn, parts: &Parts, pulled: &mut Pulled) -> Column {
    // The type is the engine's own spelling, so it is already in the form
    // `normalize` promises to return (ADR-0011 Amendment 3). Parsing it can
    // still fail, and it must fail loudly: a column whose type pbps cannot
    // read is not a column with no type.
    let ty = raw.ty.parse::<ColumnType>().ok().filter(|t| {
        types::normalize(t)
            .map(|normalized| &normalized == t)
            .unwrap_or(false)
    });
    let ty = match ty {
        Some(ty) => ty,
        None => {
            note(
                pulled,
                &parts.name,
                format!(
                    "column `{}`.`{}` has the type `{}`, which this dialect's catalogue cannot \
                     spell. It is read back as an opaque type, so a plan will not try to change \
                     it and drift on it cannot be seen (issue #130).",
                    parts.name, raw.name, raw.ty
                ),
            );
            // Kept as the engine spelled it. A type pbps cannot normalize
            // compares unequal to every declaration, so the differ reports a
            // change it will refuse to emit rather than reporting nothing.
            ColumnType::new(raw.ty.clone(), Vec::new())
        }
    };

    // **Measured**: a generated column's expression is stored in `pg_attrdef`,
    // the same place an ordinary default lives, so the columns query hands it
    // back through `default_expr`. Kept, it would read back as
    // `DEFAULT (id * 2)` — a value computed once at insert where the live
    // column is recomputed on every write, and a declaration that recreates
    // the table would silently produce the first.
    if raw.generated {
        note(
            pulled,
            &parts.name,
            format!(
                "column `{}`.`{}` is a generated column, which this model does not hold. Its \
                 expression is `{}`, and it is **not** read back as a `default:` — a default is \
                 computed once when a row is inserted, and this is recomputed on every write.",
                parts.name,
                raw.name,
                raw.default.as_deref().unwrap_or("not readable")
            ),
        );
    }

    let identity = raw.identity.map(|id| {
        if !id.always {
            note(
                pulled,
                &parts.name,
                format!(
                    "column `{}`.`{}` is `GENERATED BY DEFAULT AS IDENTITY`, and this model holds \
                     only the seed and the increment. Read back it is indistinguishable from \
                     `GENERATED ALWAYS`, which is the one a plan would emit.",
                    parts.name, raw.name
                ),
            );
        }
        Identity {
            seed: id.seed,
            increment: id.increment,
        }
    });

    Column {
        ty,
        nullable: raw.nullable,
        // Verbatim, cast and all: see this module's own documentation — except
        // for a generated column, whose expression shares `pg_attrdef` with
        // the defaults and is not one.
        default: (!raw.generated).then(|| raw.default.clone()).flatten(),
        identity,
        description: None,
        deprecated: None,
    }
}

fn add_constraint(
    raw: &RawConstraint,
    parts: &Parts,
    table_names: &HashMap<i64, TableName>,
    table: &mut Table,
    pulled: &mut Pulled,
) {
    match raw.kind {
        // PostgreSQL 18 gives every NOT NULL a `pg_constraint` row. The column
        // already carries it, and a reader that let this fall through to the
        // check arm would report one phantom check per NOT NULL column.
        'n' => {}

        // A key whose check can be put off is a different key, and the model
        // holds neither word. Named on every kind that can carry it, before
        // the kind's own arm decides what to do with the rest of it.
        'p' | 'u' | 'f' if raw.deferrable => {
            note(
                pulled,
                &parts.name,
                format!(
                    "constraint `{}` on `{}` is `DEFERRABLE{}`, and this model holds neither \
                     word. Read back as an ordinary constraint it compares equal to one that is \
                     checked immediately — so a transaction that relies on `SET CONSTRAINTS`, or \
                     on rows that violate it in the middle of one, would break with no plan \
                     saying anything had changed. Its definition is `{}`.",
                    raw.name,
                    parts.name,
                    if raw.deferred {
                        " INITIALLY DEFERRED"
                    } else {
                        ""
                    },
                    raw.definition
                ),
            );
        }

        'p' => match parts.names(&raw.columns) {
            Ok(columns) => {
                table.primary_key = Some(PrimaryKey {
                    name: Some(raw.name.clone()),
                    columns,
                });
            }
            Err(attnum) => unresolved(pulled, parts, "primary key", &raw.name, attnum),
        },

        'u' => match parts.names(&raw.columns) {
            Ok(columns) => {
                table
                    .unique
                    .insert(raw.name.clone(), UniqueConstraint { columns });
            }
            Err(attnum) => unresolved(pulled, parts, "unique constraint", &raw.name, attnum),
        },

        'c' => {
            if !raw.validated {
                note(
                    pulled,
                    &parts.name,
                    format!(
                        "check constraint `{}` on `{}` is `NOT VALID`: it holds for new rows and \
                         has never been checked against the rows already there. This model holds \
                         only the expression, so it is read back as an ordinary check.",
                        raw.name, parts.name
                    ),
                );
            }
            table.checks.insert(
                raw.name.clone(),
                CheckConstraint {
                    // Verbatim, including the parentheses and casts the engine
                    // welded on.
                    expression: raw.definition.clone(),
                },
            );
        }

        'f' => add_foreign_key(raw, parts, table_names, table, pulled),

        'x' => note(
            pulled,
            &parts.name,
            format!(
                "`{}` on `{}` is an exclusion constraint, which this model does not hold. It is \
                 left out of the pull, so a plan cannot see it and `verify` cannot report a \
                 change to it.",
                raw.name, parts.name
            ),
        ),

        other => note(
            pulled,
            &parts.name,
            format!(
                "constraint `{}` on `{}` is of kind `{other}`, which this dialect does not read. \
                 Its definition is `{}`.",
                raw.name, parts.name, raw.definition
            ),
        ),
    }
}

fn add_foreign_key(
    raw: &RawConstraint,
    parts: &Parts,
    table_names: &HashMap<i64, TableName>,
    table: &mut Table,
    pulled: &mut Pulled,
) {
    // The same rule the check arm applies, and for the same reason: a key
    // added `NOT VALID` holds for new rows and has never been checked against
    // the rows already there. Read back as an ordinary key it compares equal to
    // one that has, and recreating it validates every existing row — which can
    // fail on data the live key legally tolerates.
    if !raw.validated {
        note(
            pulled,
            &parts.name,
            format!(
                "foreign key `{}` on `{}` is `NOT VALID`: rows already there have never been \
                 checked against it, and this model holds only the key. Read back it is an \
                 ordinary foreign key, which is one that would be validated on being recreated.",
                raw.name, parts.name
            ),
        );
    }

    let Some(references_table) = raw.ref_table.and_then(|oid| table_names.get(&oid)).cloned()
    else {
        note(
            pulled,
            &parts.name,
            format!(
                "foreign key `{}` on `{}` references a table this pull did not read, so it is \
                 left out. Its definition is `{}`.",
                raw.name, parts.name, raw.definition
            ),
        );
        return;
    };

    let Ok(columns) = parts.names(&raw.columns) else {
        unresolved(
            pulled,
            parts,
            "foreign key",
            &raw.name,
            *raw.columns.last().unwrap_or(&0),
        );
        return;
    };

    // The referenced columns are attnums **on the other table**, so this map
    // cannot answer for them. The definition carries them and is reported when
    // the pair cannot be built.
    let references_columns = match reference_columns(raw) {
        Some(names) => names,
        None => {
            note(
                pulled,
                &parts.name,
                format!(
                    "foreign key `{}` on `{}` names columns on `{references_table}` that this \
                     pull cannot resolve, so it is left out. Its definition is `{}`.",
                    raw.name, parts.name, raw.definition
                ),
            );
            return;
        }
    };

    let (Some(on_delete), Some(on_update)) = (
        referential_action(raw.on_delete),
        referential_action(raw.on_update),
    ) else {
        note(
            pulled,
            &parts.name,
            format!(
                "foreign key `{}` on `{}` is `ON DELETE {}` `ON UPDATE {}`, and this model holds \
                 no `RESTRICT`. The difference is not cosmetic — `NO ACTION` is checked at the \
                 end of the statement and can be deferred, `RESTRICT` cannot — so the key is \
                 left out rather than read back as the action it is not.",
                raw.name,
                parts.name,
                action_name(raw.on_delete),
                action_name(raw.on_update)
            ),
        );
        return;
    };

    table.foreign_keys.insert(
        raw.name.clone(),
        ForeignKey {
            columns,
            references_table,
            references_columns,
            on_delete,
            on_update,
        },
    );
}

/// The referenced columns of a foreign key, read out of its own definition.
///
/// `confkey` holds attnums on the *referenced* table, which the constrained
/// table's map cannot answer for; joining the catalog a second time to resolve
/// them would put the answer in the query file, where no test can reach it.
/// `pg_get_constraintdef` already spells them, and its shape is fixed:
/// `FOREIGN KEY (a, b) REFERENCES s.t(c, d) …`.
fn reference_columns(raw: &RawConstraint) -> Option<Vec<String>> {
    let after = raw.definition.split_once(") REFERENCES ")?.1;
    let inside = after.split_once('(')?.1.split_once(')')?.0;
    let names: Vec<String> = inside
        .split(',')
        .map(|s| unquote_ident(s.trim()))
        .filter(|s| !s.is_empty())
        .collect();
    // The two sides of a foreign key line up or it is not one, and a count
    // that disagrees means this parse read something other than what it
    // thinks. Refusing it is what keeps a misparse from becoming a plan.
    (names.len() == raw.ref_columns.len()).then_some(names)
}

/// One identifier as `pg_get_constraintdef` renders it: quoted only when it has
/// to be, and a quoted one doubles its own quotes.
fn unquote_ident(s: &str) -> String {
    match s.strip_prefix('"').and_then(|s| s.strip_suffix('"')) {
        Some(inner) => inner.replace("\"\"", "\""),
        None => s.to_owned(),
    }
}

fn add_index(raw: &RawIndex, parts: &Parts, table: &mut Table, pulled: &mut Pulled) {
    if raw.method != "btree" {
        note(
            pulled,
            &parts.name,
            format!(
                "index `{}` on `{}` uses the `{}` method, and this model holds only the default \
                 one. It is left out of the pull, so a plan cannot see it.",
                raw.name, parts.name, raw.method
            ),
        );
        return;
    }
    if raw.has_expressions || raw.columns.contains(&0) {
        note(
            pulled,
            &parts.name,
            format!(
                "index `{}` on `{}` is over an expression, which this model does not hold. It is \
                 left out of the pull, so a plan cannot see it.",
                raw.name, parts.name
            ),
        );
        return;
    }
    if raw.exclusion {
        note(
            pulled,
            &parts.name,
            format!(
                "index `{}` on `{}` enforces an exclusion constraint, which this model does not \
                 hold.",
                raw.name, parts.name
            ),
        );
        return;
    }

    let key_count = raw.key_count.min(raw.columns.len());
    let (keys, included) = raw.columns.split_at(key_count);
    let (Ok(keys), Ok(include)) = (parts.names(keys), parts.names(included)) else {
        unresolved(
            pulled,
            parts,
            "index",
            &raw.name,
            *raw.columns.last().unwrap_or(&0),
        );
        return;
    };

    // Bit 0 is DESC and bit 1 is NULLS FIRST, and the model holds only the
    // first. A default `DESC` implies `NULLS FIRST` and a default `ASC` implies
    // `NULLS LAST`, so only the two crossed spellings are a difference — those
    // are reported rather than dropped.
    let mut columns = Vec::with_capacity(keys.len());
    for (position, name) in keys.into_iter().enumerate() {
        let option = raw.options.get(position).copied().unwrap_or(0);
        let descending = option & 1 == 1;
        let nulls_first = option & 2 == 2;
        if nulls_first != descending {
            note(
                pulled,
                &parts.name,
                format!(
                    "index `{}` on `{}` orders `{name}` `{}` `NULLS {}`, and this model holds \
                     only the direction. Read back it is the default ordering for that \
                     direction, which puts the nulls at the other end.",
                    raw.name,
                    parts.name,
                    if descending { "DESC" } else { "ASC" },
                    if nulls_first { "FIRST" } else { "LAST" },
                ),
            );
        }
        columns.push(IndexColumn { name, descending });
    }

    table.indexes.insert(
        raw.name.clone(),
        Index {
            columns,
            include,
            unique: raw.unique,
            // Verbatim: see this module's own documentation.
            filter: raw.filter.clone(),
        },
    );
}

/// An attnum with no live column behind it.
///
/// This is the third thing CLAUDE.md's rule names — unreadable — and it must
/// not read as either of the other two. It happens when a pull reads the
/// constraints of a table whose columns it could not read, which is what a
/// permission the connection lacks looks like from here.
fn unresolved(pulled: &mut Pulled, parts: &Parts, kind: &str, name: &str, attnum: i32) {
    note(
        pulled,
        &parts.name,
        format!(
            "{kind} `{name}` on `{}` names column number {attnum}, which this pull did not read \
             back. It is left out rather than read back with a column missing, because a key with \
             fewer columns than it has is a different key.",
            parts.name
        ),
    );
}

#[cfg(test)]
mod tests {
    use super::*;

    fn table(oid: i64, name: &str) -> RawTable {
        RawTable {
            oid,
            schema: "app".to_owned(),
            name: name.to_owned(),
        }
    }

    fn col(table_oid: i64, attnum: i32, name: &str, ty: &str) -> RawColumn {
        RawColumn {
            table_oid,
            attnum,
            name: name.to_owned(),
            ty: ty.to_owned(),
            nullable: true,
            default: None,
            identity: None,
            generated: false,
        }
    }

    fn constraint(table_oid: i64, name: &str, kind: char) -> RawConstraint {
        RawConstraint {
            table_oid,
            name: name.to_owned(),
            kind,
            columns: Vec::new(),
            ref_columns: Vec::new(),
            ref_table: None,
            on_delete: 'a',
            on_update: 'a',
            validated: true,
            deferrable: false,
            deferred: false,
            definition: String::new(),
            index_oid: None,
        }
    }

    fn index(oid: i64, table_oid: i64, name: &str) -> RawIndex {
        RawIndex {
            oid,
            table_oid,
            name: name.to_owned(),
            unique: false,
            primary: false,
            exclusion: false,
            key_count: 1,
            columns: vec![1],
            options: vec![0],
            filter: None,
            has_expressions: false,
            method: "btree".to_owned(),
        }
    }

    fn only(pulled: &Pulled) -> &Table {
        pulled.schema.tables.values().next().expect("one table")
    }

    /// The measured shape of a table with a dropped column: the slot is gone
    /// from the pull, and `attnum` keeps the hole, so everything that refers to
    /// a column refers to it by number and not by position.
    #[test]
    fn a_column_is_found_by_its_attnum_and_never_by_its_position() {
        let mut pk = constraint(1, "t_pk", 'p');
        pk.columns = vec![4];
        let raw = RawCatalog {
            tables: vec![table(1, "t")],
            // attnum 3 was dropped: 1, 2, 4.
            columns: vec![
                col(1, 1, "a", "integer"),
                col(1, 2, "b", "integer"),
                col(1, 4, "d", "integer"),
            ],
            constraints: vec![pk],
            indexes: Vec::new(),
        };
        let pulled = assemble(&raw);
        assert!(pulled.warnings.is_empty(), "{:?}", pulled.warnings);
        assert_eq!(
            only(&pulled).primary_key.as_ref().unwrap().columns,
            ["d"],
            "attnum 4 is the third column, and taking it as the fourth would \
             have found nothing at all"
        );
    }

    /// An attnum with no column behind it is the third thing in CLAUDE.md's
    /// rule. It must not silently shorten the key.
    #[test]
    fn a_key_naming_a_column_the_pull_did_not_read_is_reported_and_left_out() {
        let mut pk = constraint(1, "t_pk", 'p');
        pk.columns = vec![1, 9];
        let raw = RawCatalog {
            tables: vec![table(1, "t")],
            columns: vec![col(1, 1, "a", "integer")],
            constraints: vec![pk],
            indexes: Vec::new(),
        };
        let pulled = assemble(&raw);
        assert!(only(&pulled).primary_key.is_none());
        assert_eq!(pulled.limitations.len(), 1);
        assert!(pulled.warnings[0].contains("column number 9"));
    }

    /// PostgreSQL 18 catalogues every NOT NULL as a constraint row. Read as a
    /// check, each one would be a phantom constraint the differ tries to drop.
    #[test]
    fn a_catalogued_not_null_is_not_read_back_as_a_check() {
        let mut not_null = constraint(1, "t_a_not_null", 'n');
        not_null.columns = vec![1];
        not_null.definition = "NOT NULL a".to_owned();
        let raw = RawCatalog {
            tables: vec![table(1, "t")],
            columns: vec![col(1, 1, "a", "integer")],
            constraints: vec![not_null],
            indexes: Vec::new(),
        };
        let pulled = assemble(&raw);
        assert!(only(&pulled).checks.is_empty());
        assert!(pulled.warnings.is_empty(), "{:?}", pulled.warnings);
    }

    /// A constraint kind nobody has taught this reader about is reported, not
    /// dropped and not guessed at. The NOT NULL row above is what this rule
    /// exists for: it arrived in an engine upgrade.
    #[test]
    fn a_constraint_kind_this_reader_does_not_know_is_reported() {
        let mut odd = constraint(1, "t_odd", 'z');
        odd.definition = "SOMETHING (a)".to_owned();
        let raw = RawCatalog {
            tables: vec![table(1, "t")],
            columns: vec![col(1, 1, "a", "integer")],
            constraints: vec![odd],
            indexes: Vec::new(),
        };
        let pulled = assemble(&raw);
        assert_eq!(pulled.limitations.len(), 1);
        assert!(pulled.warnings[0].contains("kind `z`"));
        assert!(pulled.warnings[0].contains("SOMETHING (a)"));
    }

    /// The index behind a primary key or a unique constraint is that
    /// constraint. Reported twice, the differ would try to drop an index the
    /// engine does not let go of.
    #[test]
    fn the_index_that_enforces_a_constraint_is_not_reported_again_as_an_index() {
        let mut pk = constraint(1, "t_pk", 'p');
        pk.columns = vec![1];
        pk.index_oid = Some(50);
        let mut backing = index(50, 1, "t_pk");
        backing.unique = true;
        backing.primary = true;
        let raw = RawCatalog {
            tables: vec![table(1, "t")],
            columns: vec![col(1, 1, "a", "integer")],
            constraints: vec![pk],
            indexes: vec![backing, index(51, 1, "t_a_ix")],
        };
        let pulled = assemble(&raw);
        assert!(only(&pulled).primary_key.is_some());
        assert_eq!(only(&pulled).indexes.keys().collect::<Vec<_>>(), ["t_a_ix"]);
    }

    /// `RESTRICT` is not `NO ACTION`: one is checked at the end of the
    /// statement and can be deferred, the other cannot. The model holds only
    /// the first, so the key is reported rather than read back as the wrong
    /// one.
    #[test]
    fn a_foreign_key_the_model_cannot_spell_the_action_of_is_left_out_and_named() {
        let mut fk = constraint(1, "t_fk", 'f');
        fk.columns = vec![1];
        fk.ref_columns = vec![1];
        fk.ref_table = Some(2);
        fk.on_delete = 'r';
        fk.definition = "FOREIGN KEY (a) REFERENCES app.other(x) ON DELETE RESTRICT".to_owned();
        let raw = RawCatalog {
            tables: vec![table(1, "t"), table(2, "other")],
            columns: vec![col(1, 1, "a", "integer"), col(2, 1, "x", "integer")],
            constraints: vec![fk],
            indexes: Vec::new(),
        };
        let pulled = assemble(&raw);
        assert!(
            pulled.schema.tables[&TableName::new("app", "t")]
                .foreign_keys
                .is_empty()
        );
        assert!(pulled.warnings[0].contains("RESTRICT"));
    }

    /// The referenced columns are read out of the definition, because the
    /// attnums in `confkey` belong to the other table. A parse that disagrees
    /// with the count refuses rather than guesses.
    #[test]
    fn a_foreign_keys_referenced_columns_come_from_the_definition() {
        let mut fk = constraint(1, "t_fk", 'f');
        fk.columns = vec![1, 2];
        fk.ref_columns = vec![1, 2];
        fk.ref_table = Some(2);
        fk.definition =
            "FOREIGN KEY (a, b) REFERENCES app.other(\"x y\", z) ON UPDATE CASCADE".to_owned();
        fk.on_update = 'c';
        let raw = RawCatalog {
            tables: vec![table(1, "t"), table(2, "other")],
            columns: vec![
                col(1, 1, "a", "integer"),
                col(1, 2, "b", "integer"),
                col(2, 1, "x y", "integer"),
                col(2, 2, "z", "integer"),
            ],
            constraints: vec![fk],
            indexes: Vec::new(),
        };
        let pulled = assemble(&raw);
        let key = &pulled.schema.tables[&TableName::new("app", "t")].foreign_keys["t_fk"];
        assert_eq!(key.references_columns, ["x y", "z"]);
        assert_eq!(key.on_update, ReferentialAction::Cascade);
        assert!(pulled.warnings.is_empty(), "{:?}", pulled.warnings);
    }

    /// A definition whose column count does not match `confkey` means the parse
    /// read something other than what it thinks it read.
    #[test]
    fn a_referenced_column_list_that_does_not_match_the_catalog_is_refused() {
        let mut fk = constraint(1, "t_fk", 'f');
        fk.columns = vec![1];
        fk.ref_columns = vec![1, 2];
        fk.ref_table = Some(2);
        fk.definition = "FOREIGN KEY (a) REFERENCES app.other(x)".to_owned();
        let raw = RawCatalog {
            tables: vec![table(1, "t"), table(2, "other")],
            columns: vec![col(1, 1, "a", "integer"), col(2, 1, "x", "integer")],
            constraints: vec![fk],
            indexes: Vec::new(),
        };
        let pulled = assemble(&raw);
        assert!(
            pulled.schema.tables[&TableName::new("app", "t")]
                .foreign_keys
                .is_empty()
        );
        assert!(pulled.warnings[0].contains("cannot resolve"));
    }

    /// The key columns and the `INCLUDE` payload are one list in the catalog,
    /// split at `indnkeyatts`.
    #[test]
    fn an_index_splits_its_key_from_its_include_at_the_catalogs_own_count() {
        let mut ix = index(50, 1, "t_ix");
        ix.key_count = 2;
        ix.columns = vec![3, 1, 2];
        ix.options = vec![1, 0, 0];
        ix.filter = Some("(c IS NOT NULL)".to_owned());
        let raw = RawCatalog {
            tables: vec![table(1, "t")],
            columns: vec![
                col(1, 1, "a", "integer"),
                col(1, 2, "b", "integer"),
                col(1, 3, "c", "integer"),
            ],
            constraints: Vec::new(),
            indexes: vec![ix],
        };
        let pulled = assemble(&raw);
        let read = &only(&pulled).indexes["t_ix"];
        assert_eq!(read.columns[0].name, "c");
        assert!(read.columns[0].descending, "indoption bit 0 is DESC");
        assert_eq!(read.columns[1].name, "a");
        assert_eq!(read.include, ["b"]);
        assert_eq!(read.filter.as_deref(), Some("(c IS NOT NULL)"));
    }

    /// `DESC` defaults to `NULLS FIRST` and `ASC` to `NULLS LAST`, so only the
    /// two crossed spellings are a difference the model cannot hold.
    #[test]
    fn only_a_null_ordering_that_is_not_its_directions_default_is_reported() {
        // Measured: the engine prints the null ordering only for the two
        // crossed spellings, `a DESC NULLS LAST` (1) and `a NULLS FIRST` (2).
        // `a` (0) and `a DESC` (3) print none, which is what makes them the
        // defaults for their direction.
        for (option, reported) in [(0, false), (1, true), (2, true), (3, false)] {
            let mut ix = index(50, 1, "t_ix");
            ix.options = vec![option];
            let raw = RawCatalog {
                tables: vec![table(1, "t")],
                columns: vec![col(1, 1, "a", "integer")],
                constraints: Vec::new(),
                indexes: vec![ix],
            };
            let pulled = assemble(&raw);
            assert_eq!(
                !pulled.warnings.is_empty(),
                reported,
                "indoption {option}: {:?}",
                pulled.warnings
            );
            assert!(only(&pulled).indexes.contains_key("t_ix"));
        }
    }

    /// An index this model cannot hold is named and left out, never quietly
    /// turned into an ordinary one — a `gin` index read back as a btree is a
    /// plan that drops it and builds the wrong thing.
    #[test]
    fn an_index_the_model_cannot_hold_is_named_and_left_out() {
        for (name, mutate) in [
            (
                "method",
                (|ix: &mut RawIndex| ix.method = "gin".to_owned()) as fn(&mut RawIndex),
            ),
            ("expression", |ix: &mut RawIndex| ix.has_expressions = true),
            ("expression column", |ix: &mut RawIndex| {
                ix.columns = vec![0];
            }),
            ("exclusion", |ix: &mut RawIndex| ix.exclusion = true),
        ] {
            let mut ix = index(50, 1, "t_ix");
            mutate(&mut ix);
            let raw = RawCatalog {
                tables: vec![table(1, "t")],
                columns: vec![col(1, 1, "a", "integer")],
                constraints: Vec::new(),
                indexes: vec![ix],
            };
            let pulled = assemble(&raw);
            assert!(only(&pulled).indexes.is_empty(), "{name}");
            assert_eq!(pulled.limitations.len(), 1, "{name}");
        }
    }

    /// The three verbatim expressions arrive as the engine respelled them, and
    /// this half must not tidy any of them (ADR-0009 §2, ADR-0013 §4).
    #[test]
    fn the_respelled_expressions_are_carried_through_untouched() {
        let mut column = col(1, 1, "amount", "numeric(10,2)");
        column.default = Some("(0)::numeric".to_owned());
        let mut check = constraint(1, "t_ck", 'c');
        check.definition = "CHECK ((amount >= (0)::numeric))".to_owned();
        let mut ix = index(50, 1, "t_ix");
        ix.filter = Some("(amount IS NOT NULL)".to_owned());
        let raw = RawCatalog {
            tables: vec![table(1, "t")],
            columns: vec![column],
            constraints: vec![check],
            indexes: vec![ix],
        };
        let pulled = assemble(&raw);
        let read = only(&pulled);
        assert_eq!(
            read.columns["amount"].default.as_deref(),
            Some("(0)::numeric")
        );
        assert_eq!(
            read.checks["t_ck"].expression,
            "CHECK ((amount >= (0)::numeric))"
        );
        assert_eq!(
            read.indexes["t_ix"].filter.as_deref(),
            Some("(amount IS NOT NULL)")
        );
    }

    /// A type the catalogue cannot spell is the one #130 is about, and it is
    /// read back as itself with a word said. Silence here would be a column
    /// pbps believes it understands.
    #[test]
    fn a_type_the_catalogue_cannot_spell_is_kept_and_named() {
        let raw = RawCatalog {
            tables: vec![table(1, "t")],
            columns: vec![col(1, 1, "when", "timestamp(3) with time zone")],
            constraints: Vec::new(),
            indexes: Vec::new(),
        };
        let pulled = assemble(&raw);
        assert_eq!(pulled.limitations.len(), 1);
        assert!(pulled.warnings[0].contains("issue #130"));
        assert_eq!(
            only(&pulled).columns["when"].ty.to_string(),
            "timestamp(3) with time zone",
            "kept as the engine spelled it, so the differ reports a change it \
             will refuse to emit rather than reporting nothing"
        );
    }

    /// `GENERATED BY DEFAULT` and `GENERATED ALWAYS` read back the same, and a
    /// pull that did not say so would call them equal.
    #[test]
    fn an_identity_the_model_cannot_tell_apart_is_named() {
        for (always, reported) in [(true, false), (false, true)] {
            let mut column = col(1, 1, "id", "integer");
            column.identity = Some(RawIdentity {
                always,
                seed: 5,
                increment: 2,
            });
            let raw = RawCatalog {
                tables: vec![table(1, "t")],
                columns: vec![column],
                constraints: Vec::new(),
                indexes: Vec::new(),
            };
            let pulled = assemble(&raw);
            assert_eq!(!pulled.warnings.is_empty(), reported, "always={always}");
            assert_eq!(
                only(&pulled).columns["id"].identity,
                Some(Identity {
                    seed: 5,
                    increment: 2
                })
            );
        }
    }

    /// A generated column has no home in the model, and reading it back as an
    /// ordinary column with a default it does not have would be worse than
    /// saying so.
    #[test]
    fn a_generated_column_is_named() {
        let mut column = col(1, 1, "total", "integer");
        column.generated = true;
        let raw = RawCatalog {
            tables: vec![table(1, "t")],
            columns: vec![column],
            constraints: Vec::new(),
            indexes: Vec::new(),
        };
        let pulled = assemble(&raw);
        assert_eq!(pulled.limitations.len(), 1);
        assert!(pulled.warnings[0].contains("generated column"));
    }

    /// **Measured**: a generated column's expression lives in `pg_attrdef`,
    /// where an ordinary default lives, so the query hands it back as one.
    /// Kept, it reads back as `DEFAULT (id * 2)` — computed once on insert,
    /// where the live column is recomputed on every write.
    #[test]
    fn a_generated_columns_expression_is_never_read_back_as_a_default() {
        let mut column = col(1, 1, "total", "integer");
        column.generated = true;
        column.default = Some("(id * 2)".to_owned());
        let raw = RawCatalog {
            tables: vec![table(1, "t")],
            columns: vec![column],
            constraints: Vec::new(),
            indexes: Vec::new(),
        };
        let pulled = assemble(&raw);
        assert_eq!(only(&pulled).columns["total"].default, None);
        assert!(pulled.warnings[0].contains("(id * 2)"));
        assert!(pulled.warnings[0].contains("every write"));
    }

    /// A key whose check can be deferred is a different key, and the model has
    /// neither word. It is left out, like every other property of an object
    /// this model cannot hold.
    #[test]
    fn a_deferrable_key_is_left_out_and_named_whatever_kind_it_is() {
        for kind in ['p', 'u', 'f'] {
            let mut c = constraint(1, "t_key", kind);
            c.columns = vec![1];
            c.ref_columns = vec![1];
            c.ref_table = Some(1);
            c.definition = "UNIQUE (a) DEFERRABLE INITIALLY DEFERRED".to_owned();
            c.deferrable = true;
            c.deferred = true;
            let raw = RawCatalog {
                tables: vec![table(1, "t")],
                columns: vec![col(1, 1, "a", "integer")],
                constraints: vec![c],
                indexes: Vec::new(),
            };
            let pulled = assemble(&raw);
            let read = only(&pulled);
            assert!(read.primary_key.is_none(), "{kind}");
            assert!(read.unique.is_empty(), "{kind}");
            assert!(read.foreign_keys.is_empty(), "{kind}");
            assert_eq!(pulled.limitations.len(), 1, "{kind}");
            assert!(pulled.warnings[0].contains("DEFERRABLE INITIALLY DEFERRED"));
        }
    }

    /// `DEFERRABLE` without `INITIALLY DEFERRED` is still a key `SET
    /// CONSTRAINTS` can move, so it is named too — and the message says which
    /// of the two it is.
    #[test]
    fn a_deferrable_key_that_is_initially_immediate_is_named_as_that() {
        let mut c = constraint(1, "t_key", 'u');
        c.columns = vec![1];
        c.deferrable = true;
        c.deferred = false;
        let raw = RawCatalog {
            tables: vec![table(1, "t")],
            columns: vec![col(1, 1, "a", "integer")],
            constraints: vec![c],
            indexes: Vec::new(),
        };
        let pulled = assemble(&raw);
        assert!(only(&pulled).unique.is_empty());
        assert!(
            pulled.warnings[0].contains("`DEFERRABLE`"),
            "{:?}",
            pulled.warnings
        );
        assert!(!pulled.warnings[0].contains("INITIALLY DEFERRED"));
    }

    /// A foreign key added `NOT VALID` is carried — the key is exactly what the
    /// model says — and named, because recreating it validates rows the live
    /// key legally tolerates. The same rule the check arm follows.
    #[test]
    fn a_not_valid_foreign_key_is_carried_and_named() {
        let mut fk = constraint(1, "t_fk", 'f');
        fk.columns = vec![1];
        fk.ref_columns = vec![1];
        fk.ref_table = Some(2);
        fk.validated = false;
        fk.definition = "FOREIGN KEY (a) REFERENCES app.other(x) NOT VALID".to_owned();
        let raw = RawCatalog {
            tables: vec![table(1, "t"), table(2, "other")],
            columns: vec![col(1, 1, "a", "integer"), col(2, 1, "x", "integer")],
            constraints: vec![fk],
            indexes: Vec::new(),
        };
        let pulled = assemble(&raw);
        assert!(
            pulled.schema.tables[&TableName::new("app", "t")]
                .foreign_keys
                .contains_key("t_fk")
        );
        assert_eq!(pulled.limitations.len(), 1);
        assert!(pulled.warnings[0].contains("NOT VALID"));
    }

    /// Every limitation carries its table, so a caller can tell drift inside
    /// the managed set from a fact about somebody else's table.
    #[test]
    fn every_limitation_names_the_table_it_belongs_to() {
        let mut column = col(2, 1, "total", "integer");
        column.generated = true;
        let raw = RawCatalog {
            tables: vec![table(1, "plain"), table(2, "odd")],
            columns: vec![col(1, 1, "a", "integer"), column],
            constraints: Vec::new(),
            indexes: Vec::new(),
        };
        let pulled = assemble(&raw);
        assert_eq!(pulled.limitations.len(), 1);
        assert_eq!(pulled.limitations[0].table, TableName::new("app", "odd"));
        assert_eq!(pulled.warnings.len(), pulled.limitations.len());
    }

    /// A table with nothing on it is a table, not a warning. The negative case
    /// for every rule above.
    #[test]
    fn an_ordinary_table_produces_no_warning_at_all() {
        let mut pk = constraint(1, "t_pk", 'p');
        pk.columns = vec![1];
        pk.index_oid = Some(50);
        let mut backing = index(50, 1, "t_pk");
        backing.unique = true;
        backing.primary = true;
        let mut column = col(1, 1, "id", "integer");
        column.nullable = false;
        let raw = RawCatalog {
            tables: vec![table(1, "t")],
            columns: vec![column, col(1, 2, "note", "text")],
            constraints: vec![pk],
            indexes: vec![backing],
        };
        let pulled = assemble(&raw);
        assert!(pulled.warnings.is_empty(), "{:?}", pulled.warnings);
        assert!(pulled.limitations.is_empty());
        let read = only(&pulled);
        assert_eq!(read.columns.len(), 2);
        assert!(!read.columns["id"].nullable);
        assert!(read.columns["note"].nullable);
        assert!(read.indexes.is_empty());
    }
}
