//! Read-only environment discovery (ADR-0016 decision 4), not plan evidence.
//!
//! These are connected report shapes, like `doctor::Ask`. Engine crates own
//! the queries and candidate rules. Discovery cannot construct a qualified
//! resolver or authorize compilation, publication or apply.

pub mod capture;
pub mod environment;

use std::collections::BTreeMap;

/// Read-only engine observations for a native runtime admission check. They
/// are not globally unique instance proofs: clones can retain these values.
/// The caller must bind them to the actual kernel process and connection.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct InstanceObservation {
    pub instance_key: String,
    pub process: BackendProcess,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum BackendProcess {
    NativePid(std::num::NonZeroU32),
    /// SQL Server's PAL process number is not its native Linux socket owner.
    RuntimeOnly,
}

/// Run-owned scratch resource names, generated by the lifecycle owner and
/// quoted by each engine adapter. The constructor is the only way to build
/// one, so an injected identifier or an empty name cannot be represented.
#[derive(Clone, PartialEq, Eq)]
pub struct ScratchNames {
    database: String,
    login: String,
    password: String,
}

/// The credential never reaches `Debug`, diagnostics or saved evidence.
impl std::fmt::Debug for ScratchNames {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter
            .debug_struct("ScratchNames")
            .field("database", &self.database)
            .field("login", &self.login)
            .finish_non_exhaustive()
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, thiserror::Error)]
#[error("scratch resource names must be run-generated pbps identifiers")]
pub struct UnsupportedScratchName;

impl ScratchNames {
    /// Accepts only the generated shape: an ASCII lowercase `pbps_` name of
    /// bounded length and a hexadecimal credential. Quoting then cannot be
    /// the only thing standing between a run name and an injected statement.
    pub fn new(
        database: String,
        login: String,
        password: String,
    ) -> Result<Self, UnsupportedScratchName> {
        let identifier = |value: &str| {
            value.len() >= 6
                && value.len() <= 48
                && value.starts_with("pbps_")
                && value
                    .bytes()
                    .all(|b| b.is_ascii_lowercase() || b.is_ascii_digit() || b == b'_')
        };
        if !identifier(&database)
            || !identifier(&login)
            || database == login
            || password.len() < 32
            || password.len() > 128
            || !password.bytes().all(|b| b.is_ascii_hexdigit())
        {
            return Err(UnsupportedScratchName);
        }
        Ok(Self {
            database,
            login,
            password,
        })
    }

    pub fn database(&self) -> &str {
        &self.database
    }
    pub fn login(&self) -> &str {
        &self.login
    }
    pub fn password(&self) -> &str {
        &self.password
    }
}

/// What a session can learn about *itself* without privilege.
///
/// Measured on PostgreSQL 18 and SQL Server 2025: a run-owned login sees only
/// its own row in the engine's session views, and `VIEW SERVER STATE` and
/// `pg_read_all_stats` are exactly what it does not have. Its own key it can
/// always read, and that is all the census needs from it — the privileged
/// inventory belongs to the connection that has the rights for it.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct OwnSession {
    pub key: String,
    pub process: BackendProcess,
}

/// The engine's own answer about who is connected to it. This is a second,
/// independent signal: the runtime exclusion strategy decides admission, and
/// a server that cannot report its client sessions is unanswerable, not idle.
/// The cumulative session counter and what it is counted against.
///
/// A total on its own can be made to come back down: PostgreSQL keeps its
/// per-database and a dropped database takes its share of the sum with it.
/// `continuity` names the rows the total was summed over, so one of them
/// disappearing is visible even when the arithmetic works out.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SessionCounter {
    pub total: u64,
    /// Where the counter started; a change means it restarted.
    pub epoch: String,
    /// Identities the total is summed over. Empty for an engine whose
    /// counter is a single server-level value that nothing can remove.
    pub continuity: Vec<String>,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SessionInventory {
    /// This connection's own engine-visible session key.
    pub own: String,
    /// Every client session key the engine reports, including `own`.
    pub clients: Vec<String>,
    /// The cumulative counter as read alongside this list.
    pub counter: SessionCounter,
}

#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, schemars::JsonSchema)]
#[serde(tag = "status", rename_all = "kebab-case")]
pub enum Observation {
    Observed {
        value: String,
    },
    /// SQL NULL: absent, hidden or unsupported cannot be distinguished here.
    NotReported,
    Unknown {
        reason: String,
    },
}

impl Observation {
    pub fn reported(value: Option<&str>) -> Self {
        match value {
            Some(value) => Self::Observed {
                value: value.into(),
            },
            None => Self::NotReported,
        }
    }

    pub fn value(&self) -> Option<&str> {
        match self {
            Self::Observed { value } => Some(value),
            Self::NotReported | Self::Unknown { .. } => None,
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, schemars::JsonSchema)]
#[serde(tag = "status", rename_all = "kebab-case")]
pub enum Candidate {
    Suggested { image: String },
    Unavailable { reason: String },
}

#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, schemars::JsonSchema)]
pub struct Extension {
    pub name: String,
    pub schema: String,
    pub version: String,
}

/// A separate single-variant type prevents an advisory query from claiming
/// the verified compatibility reserved for a qualified backend/run.
#[derive(Debug, Clone, Copy, PartialEq, Eq, serde::Serialize, schemars::JsonSchema)]
#[serde(rename_all = "kebab-case")]
pub enum DiscoveryCompatibility {
    Unverified,
}

#[derive(Debug, Clone, PartialEq, Eq, serde::Serialize, schemars::JsonSchema)]
pub struct Discovery {
    /// Observations describe this introspection session, not the future
    /// deployment's per-statement settings or authorization. No consistent
    /// evidence capture, fingerprint or compatibility comparison is implied.
    pub observations: BTreeMap<String, Observation>,
    /// PostgreSQL's installed extension inventory, without definitions or
    /// native-library identities. None means this inventory is not applicable
    /// to the engine; a failed inventory query returns an error instead.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub extensions: Option<Vec<Extension>>,
    pub candidate: Candidate,
    pub compatibility: DiscoveryCompatibility,
    /// Conditions discovery cannot establish. These remain advisory to
    /// ordinary deployment readiness, never proof that resolution can run.
    pub qualification: BTreeMap<String, Observation>,
}

impl Discovery {
    pub fn unverified(
        observations: BTreeMap<String, Observation>,
        extensions: Option<Vec<Extension>>,
        candidate: Candidate,
    ) -> Self {
        let qualification = [
            ("engine-and-native-builds", "Qualify the actual backend's loaded and required executable content; reported versions alone do not prove compatibility."),
            ("deployment-context", "Qualify per-statement deployment settings, authorization, memberships, ownership and visibility; introspection-session observations are not that context."),
            ("candidate-compatibility", "Verify the running candidate against the required engine/product, versions, extensions, locale and settings; an image suggestion is not a match."),
            ("transport", "Qualify authenticated peer-verified evidence channels before accepting evidence or transferring declarations."),
            ("instance-separation", "Prove that the actual resolver backend is outside the target cluster or instance before scratch DDL."),
            ("execution-containment", "Qualify runtime-enforced network/filesystem containment, bounded resources and lifetime."),
            ("run-stability", "Qualify backend continuity and protection against relevant in-place changes throughout compilation."),
            ("private-input-handling", "If external definitions are needed, qualify private transport, logging and storage of their source; their fingerprints are keyed to the environment (DEC-952.1)."),
            ("binding-adapter", "Binding resolution is not implemented; discovery cannot supply evidence or replace existing planning protections."),
        ].into_iter().map(|(key, reason)| (key.into(), Observation::Unknown { reason: reason.into() })).collect();
        Self {
            observations,
            extensions,
            candidate,
            compatibility: DiscoveryCompatibility::Unverified,
            qualification,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn only_generated_scratch_identifiers_and_credentials_are_representable() {
        let names = ScratchNames::new(
            "pbps_scratch_0123456789abcdef".into(),
            "pbps_run_0123456789abcdef".into(),
            "0".repeat(32),
        )
        .unwrap();
        assert_eq!(names.database(), "pbps_scratch_0123456789abcdef");
        assert!(!format!("{names:?}").contains(names.password()));
        for (database, login, password) in [
            (
                "scratch".to_owned(),
                "pbps_run_a1".to_owned(),
                "0".repeat(32),
            ),
            (
                "pbps_a\"; DROP".to_owned(),
                "pbps_run_a1".to_owned(),
                "0".repeat(32),
            ),
            (
                "pbps_Scratch".to_owned(),
                "pbps_run_a1".to_owned(),
                "0".repeat(32),
            ),
            (
                "pbps_same".to_owned(),
                "pbps_same".to_owned(),
                "0".repeat(32),
            ),
            (
                "pbps_scratch".to_owned(),
                "pbps_run_a1".to_owned(),
                "0".repeat(31),
            ),
            (
                "pbps_scratch".to_owned(),
                "pbps_run_a1".to_owned(),
                format!("{}g", "0".repeat(32)),
            ),
            (
                "pbps_".to_owned() + &"a".repeat(44),
                "pbps_run_a1".to_owned(),
                "0".repeat(32),
            ),
        ] {
            assert_eq!(
                ScratchNames::new(database, login, password),
                Err(UnsupportedScratchName)
            );
        }
    }

    #[test]
    fn unreported_and_unknown_facts_cannot_be_read_as_observed_empty_values() {
        assert_eq!(Observation::reported(Some("")).value(), Some(""));
        for fact in [
            Observation::reported(None),
            Observation::Unknown {
                reason: "not qualified".into(),
            },
        ] {
            assert_eq!(fact.value(), None);
            assert!(serde_json::to_value(fact).unwrap().get("value").is_none());
        }
    }
}
