[package]
name = "pbps-mssql"
description = "PongBiphang Schema - the Microsoft SQL Server dialect"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
pbps-model.workspace = true
pbps-dialect.workspace = true
pbps-db.workspace = true
serde_json.workspace = true
tiberius.workspace = true

[dev-dependencies]
pbps-diff.workspace = true
tokio = { workspace = true, features = ["macros", "rt"] }

[lints]
workspace = true
