[package]
name = "pbps-cli"
description = "PongBiphang Schema - declarative database schema version control"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "pbps"
path = "src/main.rs"

[dependencies]
pbps-model.workspace = true
pbps-config.workspace = true
pbps-load.workspace = true
pbps-diff.workspace = true
pbps-dialect.workspace = true
clap.workspace = true
anyhow.workspace = true
miette = { workspace = true, features = ["fancy"] }
serde_json.workspace = true

[lints]
workspace = true

[dev-dependencies]
serde_json.workspace = true
